/**
 * Category-Specific Content
 *
 * All category-specific quotes, symptoms, failed alternatives, motivations, etc.
 * This is the SINGLE SOURCE OF TRUTH for category content used in simulation.
 */

import type { ParticipantArchetype } from '../types';

// ============================================================================
// CATEGORY + ARCHETYPE SPECIFIC QUOTES
// These are the verbatim quotes participants share about their journey.
// Organized by category, then by archetype personality type.
// ============================================================================

export const CATEGORY_ARCHETYPE_QUOTES: Record<string, Record<ParticipantArchetype, string[]>> = {
  sleep: {
    desperate: [
      "I haven't slept through the night in 3 years. I've tried everything - melatonin, prescription pills, therapy. This is my last hope.",
      "My insomnia is destroying my marriage. I'm too exhausted to be present for my kids. I need this to work.",
      "I've spent thousands on sleep specialists and supplements. Nothing has worked for more than a week. I'm desperate.",
      "The bags under my eyes are permanent now. I can't remember the last time I woke up feeling rested. Please work.",
      "I'm so tired I made a dangerous mistake at work last week. I need to fix this before something worse happens.",
    ],
    skeptic: [
      "I've been burned by 'miracle sleep supplements' before. But my friend swears by this, so I'll give it a shot.",
      "The science looks decent, but I'm not expecting miracles. If I can fall asleep even 15 minutes faster, I'll call it a win.",
      "Another sleep product... we'll see. I'm tracking everything so I'll know if it actually works or if it's placebo.",
      "I'm joining mostly to see the data. Not convinced yet, but willing to try.",
    ],
    power_user: [
      "My Oura shows 4 hours of deep sleep average, but I want 5+. Looking for that last optimization lever.",
      "I've dialed in sleep hygiene, temperature, light exposure. Supplements are the final frontier for my sleep stack.",
      "My HRV tanks when I don't sleep well. Curious if this can help me maintain consistency in my recovery metrics.",
      "I track everything. If this moves my sleep efficiency from 85% to 90%, it's worth it.",
    ],
    struggler: [
      "The racing thoughts at night are exhausting. I just want my brain to quiet down so I can sleep.",
      "I wake up at 3am every night and stare at the ceiling. It's been months of this and I'm worn down.",
      "Sleep used to be easy. Now it's the hardest part of my day. Something changed and I need help fixing it.",
      "I'm not a complete insomniac, but I never feel rested. It's affecting everything else in my life.",
    ],
    optimist: [
      "My friend started sleeping like a baby after trying this. Can't wait to see what it does for me!",
      "I've heard great things and I'm excited to finally prioritize my sleep. Ready for better mornings!",
      "Even if my sleep is okay, I know it could be better. Excited to level up!",
    ],
  },
  stress: {
    desperate: [
      "My anxiety is so bad I've started having panic attacks at work. I'm on the verge of taking medical leave.",
      "I can't stop the racing thoughts. They follow me everywhere - work, home, even trying to relax. I need relief.",
      "The tension in my body is constant. My jaw hurts from clenching, my shoulders are rocks. I'm falling apart.",
      "I've been on anti-anxiety meds for years. I want to find something that helps me depend on them less.",
      "Stress has taken over my life. My relationships are suffering, my health is declining. I have to do something.",
      "I wake up with dread every morning. The Sunday scaries have become everyday scaries. I'm burning out.",
      "My doctor says my cortisol is chronically elevated. I'm aging myself with stress. I need to break this cycle.",
      "I've developed a tremor from stress. My body is physically breaking down and I'm terrified.",
    ],
    skeptic: [
      "Stress supplements usually just make expensive pee. But I'll track my HRV and see if this one's different.",
      "I'm skeptical of anything that claims to 'reduce stress' - it's such a vague promise. We'll see.",
      "My therapist suggested trying supplements alongside therapy. Not expecting much, but worth a shot.",
      "I've tried ashwagandha, L-theanine, magnesium — none made a noticeable difference. Prove me wrong.",
      "If managing stress were as easy as taking a pill, everyone would be calm. I'll track outcomes carefully.",
    ],
    power_user: [
      "I've optimized most variables but my HRV still tanks during stressful weeks. Looking for adaptogenic support.",
      "I meditate daily and exercise regularly. Adding targeted supplementation to complete my stress resilience stack.",
      "My Whoop shows my strain-to-recovery ratio is off. Need something to help my body adapt better.",
      "I track my HRV religiously. I know exactly when stress is hitting my body. Looking for something to blunt the impact.",
      "I've got the lifestyle factors dialed in. Supplementation is the missing piece in my stress protocol.",
    ],
    struggler: [
      "Work pressure just keeps building. I used to handle it fine, but now I feel on edge constantly.",
      "The worry follows me home. I can't enjoy evenings with my family because my mind is still at work.",
      "I know I need to manage stress better. This seems like a good place to start.",
      "Tension headaches are becoming weekly. The stress is literally hurting me now.",
      "I'm not in crisis, but I'm never truly relaxed either. I want to know what calm actually feels like.",
      "The background hum of stress is always there. I've normalized it but I shouldn't have to.",
    ],
    optimist: [
      "Life is good but busy! Looking forward to having a tool in my toolkit for the hectic days.",
      "I believe in proactive wellness. Why wait until stress becomes a problem?",
      "Excited to feel even more calm and centered. Already do yoga, this is the next step!",
      "Stress is part of life but I want to ride the waves better. Ready to build resilience!",
    ],
  },
  energy: {
    desperate: [
      "I'm exhausted from the moment I wake up. Coffee doesn't even work anymore. I have no life outside of surviving.",
      "The afternoon crash is ruining my career. I can barely function after 2pm. Something has to change.",
      "I've had every blood test done. Everything's 'normal' but I feel like I'm running on empty constantly.",
      "My energy is so low I had to cut back my work hours. I can't afford to keep declining like this.",
      "I used to be full of energy. Now I'm a shell of myself. I need to find what's missing.",
    ],
    skeptic: [
      "Energy supplements are usually just caffeine in disguise. I'll track my energy levels carefully.",
      "I've tried B vitamins, iron, everything. Doubtful this will be different, but I'm running out of options.",
      "The ingredient list looks interesting. I'll give it a fair trial before I judge.",
    ],
    power_user: [
      "My energy is good but not great. Looking for consistent optimization without stimulant dependency.",
      "I've cut caffeine to reduce the crashes. Looking for something that provides sustained energy naturally.",
      "My continuous glucose monitor shows stable levels. Time to optimize the other energy levers.",
    ],
    struggler: [
      "The 2pm wall hits me every single day. I've tried everything to push through it.",
      "By evening I have nothing left. My family gets the tired, irritable version of me.",
      "I'm not sleeping poorly, but I never feel energized. Something's off.",
      "I've accepted low energy as my normal. But I want to see if normal can be better.",
    ],
    optimist: [
      "I'm already pretty energetic, but more sustainable energy sounds amazing!",
      "Ready to go from good energy to great energy. Let's do this!",
      "If I can skip the afternoon coffee and still feel great, that's a win.",
    ],
  },
  focus: {
    desperate: [
      "I can't finish a single task anymore. My ADHD has gotten worse and medication isn't enough.",
      "I'm making mistakes at work I never used to make. My job is at risk because I can't concentrate.",
      "Brain fog has taken over my life. I used to be sharp. Now I feel like I'm thinking through molasses.",
      "I've tried every focus app, every technique. Nothing sticks. I'm losing my edge.",
    ],
    skeptic: [
      "Nootropics are usually overhyped. But the research on these ingredients is interesting.",
      "I'll track my focused work time objectively. Either it helps or it doesn't.",
      "Not expecting a miracle, but even 10% improvement in focus would be worthwhile.",
    ],
    power_user: [
      "I've optimized my environment and routines. Looking for the cognitive edge that comes from proper supplementation.",
      "My work requires intense concentration. I need sustainable focus, not stimulant peaks and crashes.",
      "I track my deep work hours. Looking to go from 4 hours to 6 hours of quality focus time.",
    ],
    struggler: [
      "I start tasks with good intentions but my mind wanders within minutes. It's frustrating.",
      "Reading has become impossible. I re-read the same paragraph over and over.",
      "The mental fog makes everything harder. Simple decisions feel overwhelming.",
    ],
    optimist: [
      "I'm already pretty focused, but sharpening that edge sounds great for my career!",
      "Excited to see what I can accomplish with better concentration.",
    ],
  },
  recovery: {
    desperate: [
      "My HRV has been in the red for months. I'm overtraining but can't afford to stop. Need faster recovery.",
      "I'm sore for 4-5 days after every workout. My training is suffering because I can't recover.",
      "Used to recover overnight. Now it takes me a week to feel ready again. Something's broken.",
      "My performance has plateaued. I think it's a recovery problem, not a training problem.",
      "I'm 42 and my body just doesn't bounce back anymore. I've tried every recovery supplement on the market.",
      "Competition is in 8 weeks and I'm breaking down instead of peaking. I'm desperate for faster recovery.",
      "Every hard workout puts me out of commission for days. I can only train twice a week now. It's devastating.",
    ],
    skeptic: [
      "Recovery supplements are a dime a dozen. I'll track my HRV and soreness objectively.",
      "The ingredient profile looks solid, but I've been disappointed before.",
      "My coach suggested this. Willing to try it for a proper training block.",
      "Recovery products are usually just expensive placebos. Show me the data — I track everything.",
      "I've tried BCAAs, glutamine, tart cherry — none moved the needle. Skeptical but trying anyway.",
    ],
    power_user: [
      "My Whoop recovery scores average 60%. I want to consistently hit 75%+.",
      "I've optimized sleep and nutrition. Supplementation for recovery is the next optimization layer.",
      "Looking to reduce DOMS and improve my HRV response to hard training days.",
      "I track recovery religiously — HRV, resting HR, grip strength, jump height. Ready to see if this moves metrics.",
      "My training load is dialed in. Recovery is the remaining variable to optimize.",
      "I'm looking for that 5% edge. In my sport, that's the difference between podium and pack.",
    ],
    struggler: [
      "I love training but the soreness keeps me sidelined. Want to train more consistently.",
      "My recovery is unpredictable. Some days I bounce back, others I'm wrecked.",
      "Age is catching up to me. Recovery isn't what it used to be.",
      "I want to train 5 days a week but my body only tolerates 3. Recovery is the bottleneck.",
      "The day after leg day is brutal. I need to be functional for work, not hobbling around.",
      "I feel great during workouts but pay for it the next two days. Looking for help.",
    ],
    optimist: [
      "Ready to train harder knowing I can recover faster!",
      "Excited to see what I can do when recovery isn't the limiting factor.",
      "I recover pretty well but I know there's room for improvement. Let's optimize!",
      "Looking to shave recovery time so I can increase training frequency.",
    ],
  },
  gut: {
    desperate: [
      "I'm bloated after every single meal. It doesn't matter what I eat. My stomach is constantly distended and painful.",
      "I've been to three GI specialists and done every test. IBS diagnosis but no real solution. I'm desperate for relief.",
      "My gut issues have taken over my life. I plan every outing around bathroom access. I can't live like this anymore.",
      "The cramping is unbearable some days. I've missed work, cancelled plans, cried in pain. Nothing helps consistently.",
      "I've eliminated dairy, gluten, FODMAPs, everything. Still bloated, still miserable. I need something to work.",
      "My digestion is ruining my relationship. I'm too uncomfortable to be intimate, too self-conscious about bloating.",
      "Food has become my enemy. I'm afraid to eat because I know pain is coming. This isn't living.",
    ],
    skeptic: [
      "I've tried every probiotic on the market. Most did nothing, some made things worse. I'll track symptoms carefully.",
      "The gut microbiome science is interesting, but I'm not convinced any supplement can really fix deep-rooted issues.",
      "My doctor is skeptical of gut supplements. But I'm running out of options, so I'll give it a fair trial.",
      "Every gut product promises miracles. I'll track my bloating, bowel movements, and pain levels objectively.",
      "I've been burned by expensive probiotics before. This one better have real data behind it.",
    ],
    power_user: [
      "I've optimized my diet and identified my triggers. Looking for the supplement piece to complete my gut protocol.",
      "I track my meals and symptoms in an app. Ready to see if this adds measurable improvement to my baseline.",
      "I've done the elimination diets, the gut testing, the whole nine yards. This is about fine-tuning.",
      "My gut is 80% better since I fixed my diet. Looking for that last 20% improvement.",
    ],
    struggler: [
      "Some days my gut is fine, others it's terrible. I can't figure out the pattern and it's exhausting.",
      "The bloating isn't severe but it's constant. I never feel comfortable in my own body.",
      "I've had minor gut issues for years and finally decided to actually address them instead of just dealing with it.",
      "After eating I feel heavy and sluggish. My digestion just isn't what it used to be.",
      "I'm not in pain, but I'm never truly comfortable either. There has to be a better normal.",
    ],
    optimist: [
      "I've heard gut health affects everything — mood, energy, skin. Excited to see the ripple effects!",
      "My friend's digestion transformed with this. Can't wait to experience it myself!",
      "I'm already pretty healthy but I know my gut could be better. Ready to optimize!",
      "Investing in gut health feels like the foundation for everything else. Let's do this!",
    ],
  },
  weight: {
    desperate: [
      "I've lost the same 20 pounds five times. It always comes back, plus more. I'm heavier than I've ever been.",
      "My doctor says I need to lose weight for my health, but nothing I do works long-term. I'm running out of options.",
      "I've tried every diet imaginable — keto, paleo, intermittent fasting, calorie counting. I lose, then regain. Every time.",
      "I don't recognize my body anymore. I'm exhausted from the constant battle. Something has to give.",
      "The weight is affecting my joints, my energy, my confidence. I need a sustainable solution, not another quick fix.",
      "I've spent thousands on weight loss programs. Some worked temporarily. None stuck. I'm desperate for something different.",
      "My metabolism feels completely broken. I eat less than my thin friends and gain weight. It's not fair and I'm tired.",
    ],
    skeptic: [
      "Weight loss supplements are usually garbage. But this one has interesting research. I'll track everything and see.",
      "I don't believe in magic pills. If this helps with satiety or energy, great. But I'm not expecting miracles.",
      "I've been disappointed by weight loss products before. My expectations are low but I'm willing to try.",
      "The only thing that's ever worked is calories in, calories out. I'll see if this actually makes that easier.",
      "I'm joining to prove this doesn't work, honestly. But I'll give it a fair shot.",
    ],
    power_user: [
      "I've dialed in my nutrition and exercise. Looking for the metabolic support to push past this plateau.",
      "I track macros, steps, everything. Ready to see if this supplement moves the needle on my body composition.",
      "I'm in decent shape but want to get to the next level. Diet and exercise alone aren't getting me there.",
      "My weight is stable but I can't seem to lose the last 10 pounds no matter what I do.",
    ],
    struggler: [
      "I eat pretty well and exercise sometimes, but the scale won't budge. There must be something I'm missing.",
      "I've gained weight slowly over the years. It's time to actually do something about it.",
      "My clothes don't fit like they used to. I'm not desperate, but I'm ready for change.",
      "I know what to do, I just struggle to stay consistent. Maybe this will help with that.",
      "The weight crept on during a stressful period and never left. Time to address it.",
    ],
    optimist: [
      "I'm starting fresh and feeling motivated! This could be the support I need to stay on track.",
      "I've heard great things and I'm ready to commit. Excited to see what happens!",
      "New year, new approach. Let's see what's possible when I give my body what it needs!",
      "I believe in sustainable health, not quick fixes. This seems like the right approach.",
    ],
  },
  anxiety: {
    desperate: [
      "The anxiety attacks came out of nowhere and now they control my life. I'm afraid to go places, meet people, live normally.",
      "I've been on anxiety medication for years. I want to find ways to manage without being dependent on pills.",
      "My anxiety is so bad I've called in sick to work multiple times this month. I'm about to lose my job.",
      "I can't remember the last time I felt truly calm. The constant worry is exhausting and I'm breaking down.",
      "Social situations have become torture. I rehearse conversations, dread events, and feel sick with nerves constantly.",
      "My anxiety gave me an ulcer. My body is literally breaking down from the stress. I need relief now.",
      "I've been to the ER twice thinking I was having a heart attack. Both times it was anxiety. I can't keep living like this.",
    ],
    skeptic: [
      "I've tried meditation apps, breathing exercises, even therapy. They help a little but not enough. Not sure a supplement can fix this.",
      "The mind-body connection is real, but I'm skeptical any supplement can meaningfully reduce anxiety.",
      "My therapist suggested trying supplements alongside our work. I'm doubtful but willing to try.",
      "I'll track my anxiety levels carefully. Either this helps or it doesn't — I won't convince myself it works if it doesn't.",
      "Every 'calming' supplement I've tried has been a waste of money. Hoping this is different.",
    ],
    power_user: [
      "I've built a solid anxiety management toolkit — therapy, exercise, meditation. Looking for additional support.",
      "My baseline anxiety has improved but I still struggle during high-stress periods. Need something to smooth out the spikes.",
      "I track my mood and stress levels daily. Ready to see if this supplement adds measurable benefit.",
      "I've optimized everything else. Supplementation is the next frontier in my anxiety management protocol.",
    ],
    struggler: [
      "I'm not having panic attacks, but the background worry is always there. I'd love to know what calm actually feels like.",
      "Work stress builds up throughout the week. By Friday I'm a ball of tension. There has to be a better way.",
      "I've always been a worrier but it's gotten worse. Time to actually address it instead of accepting it.",
      "The anxious thoughts are loudest at night. I lie awake running through everything that could go wrong.",
      "I'm functional but not thriving. The constant low-level anxiety is draining my energy and joy.",
    ],
    optimist: [
      "I manage my anxiety pretty well but I'm always looking for tools to feel even more grounded!",
      "Life is stressful but manageable. I want to go from coping to thriving!",
      "Excited to add this to my wellness routine. Every little bit of calm helps!",
      "I believe in proactive mental health. Why wait until anxiety becomes a crisis?",
    ],
  },
  mood: {
    desperate: [
      "I feel flat. Not depressed exactly, but like all the color has drained out of life. I miss feeling joy.",
      "The mood swings are destroying my relationships. I never know which version of me will show up each day.",
      "I've been in a funk for months. Nothing is technically wrong but nothing feels right either. I need to break out of this.",
      "My family walks on eggshells around me because my mood is so unpredictable. I hate who I've become.",
      "I used to be the positive one. Now I'm irritable, short-tempered, and struggle to enjoy anything. What happened to me?",
      "Some days I'm fine, other days I can barely get out of bed. The inconsistency is exhausting for everyone around me.",
      "I've been on antidepressants but the side effects are awful. Looking for something that doesn't make me feel like a zombie.",
    ],
    skeptic: [
      "Mood supplements usually make big promises. I'll track my daily mood scores and see if there's any real difference.",
      "I'm skeptical anything can shift baseline mood, but the research on this looks interesting.",
      "I've tried St. John's Wort, SAM-e, various things. Nothing has made a significant difference.",
      "My psychiatrist thinks supplements are mostly placebo. I'll find out for myself.",
      "I don't believe in quick fixes for mood. But I'm open to something that supports my other efforts.",
    ],
    power_user: [
      "I've optimized sleep, exercise, and diet. Looking for the supplement piece to complete my mood optimization stack.",
      "I track my mood daily in an app. Ready to see objective data on whether this makes a difference.",
      "My baseline mood is good but I want it to be great. Looking for consistent elevation, not just preventing lows.",
      "I've done the therapy work. Now I'm adding targeted supplementation to maintain my gains.",
    ],
    struggler: [
      "I'm not depressed, just... meh. I want to actually look forward to things again.",
      "The afternoon slump hits my mood hard. By evening I'm cranky and withdrawn.",
      "I've noticed my mood dipping over the past year. Nothing dramatic, but enough to bother me.",
      "I used to wake up excited for the day. Now I just wake up. I want that spark back.",
      "Small things irritate me more than they should. I'd like to feel more emotionally resilient.",
    ],
    optimist: [
      "I'm already pretty positive but I love the idea of supporting my mood naturally!",
      "Excited to feel even more balanced and upbeat. Mood affects everything!",
      "Taking care of mental wellness is just as important as physical. Let's optimize!",
      "I believe happiness is a practice. This is another tool in my toolkit!",
    ],
  },
  pain: {
    desperate: [
      "I've spent $20,000 on treatments — chiropractors, physical therapy, injections. Nothing gives me more than temporary relief.",
      "The pain has stolen my life. I can't play with my kids, can't exercise, can't even sit through a movie. I'm desperate.",
      "I've been on pain medication for 5 years. My doctor wants to increase the dose again. I need another option.",
      "Some days I can barely get out of bed. The pain is always there, just waiting to flare up. I've lost hope.",
      "I've tried acupuncture, massage, CBD, heat, ice, stretching — nothing breaks the cycle. This is my last attempt.",
      "The chronic pain has destroyed my career. I had to quit a job I loved because I couldn't function anymore.",
      "My pain specialist says this is as good as it gets. I refuse to accept that. There has to be something else.",
    ],
    skeptic: [
      "I've tried every supplement, cream, and device for pain. They all promise miracles and deliver nothing.",
      "Pain is physical. I'm skeptical a supplement can address the underlying cause, but I'll track my levels.",
      "My doctor says pain supplements are mostly placebo. I'll keep a detailed pain diary to see for myself.",
      "I've been disappointed so many times. My expectations are at rock bottom, which might be a good thing.",
      "The reviews seem too good. Real chronic pain doesn't just disappear with a pill.",
    ],
    power_user: [
      "I track my pain on a 1-10 scale daily. I know my triggers, my patterns, everything. Looking for an edge.",
      "I've done all the lifestyle modifications — anti-inflammatory diet, proper sleep, stress management. Need the supplement layer.",
      "My pain varies predictably. I want to see if this can reduce my baseline or blunt the flare-ups.",
      "I've tried every combination of natural approaches. Adding this to see if it moves the needle.",
    ],
    struggler: [
      "Some days are manageable, others I'm counting the hours until I can lie down. I want more good days.",
      "The pain isn't severe, but it's constant. This low-grade discomfort is wearing me down over time.",
      "I've dealt with this for years and just accepted it. Maybe it's time to actually try to fix it.",
      "Morning stiffness sets the tone for my whole day. If I could just start the day better, everything would improve.",
      "I'm not in agony, but I'm never comfortable. I'd forgotten what it feels like to have a pain-free day.",
    ],
    optimist: [
      "Minor aches that I'd like to address before they become bigger issues. Prevention is key!",
      "I'm active and want to stay that way. Looking for joint support as I age.",
      "Occasional discomfort after workouts. Ready to recover better!",
    ],
  },
  skin: {
    desperate: [
      "I'm 35 and still breaking out like a teenager. I've tried Accutane, antibiotics, every prescription. Nothing works long-term.",
      "My skin has destroyed my confidence. I cancel plans, avoid photos, and can barely look in the mirror some days.",
      "I've spent thousands on dermatologists and medical-grade skincare. My skin still looks inflamed and angry.",
      "The rosacea makes me look like I'm constantly embarrassed or sunburned. Makeup doesn't cover it anymore.",
      "I've eliminated dairy, sugar, gluten — my skin still betrays me. I'm running out of things to try.",
      "The texture and scarring from years of acne... I just want to feel comfortable in my own skin.",
      "My skin issues started in my 20s and have only gotten worse. Every 'miracle product' has failed me.",
    ],
    skeptic: [
      "Skin health is genetics and skincare routine, not supplements. But I'll give it a fair trial and take photos.",
      "I've tried collagen, biotin, every 'beauty vitamin.' My skin looks the same. Doubtful this is different.",
      "My dermatologist is skeptical of skin supplements. I'll track my skin clarity objectively with photos.",
      "Inner beauty supplements are usually just expensive marketing. Prove me wrong.",
      "I know enough about skin science to be skeptical, but the ingredient list is intriguing.",
    ],
    power_user: [
      "I have a 12-step skincare routine and track my skin with weekly photos. Ready to add the internal piece.",
      "I've optimized my topicals — retinoids, vitamin C, niacinamide. Time to work from the inside out.",
      "I know my skin triggers. Diet and stress are handled. Looking for supplemental support.",
      "My skin is good but I want that glow. Looking for the difference between good skin and great skin.",
    ],
    struggler: [
      "My skin is just... okay. Never clear, never terrible. I want to finally have skin I'm proud of.",
      "Occasional breakouts that always seem to happen at the worst times. Want more consistency.",
      "My skin has gotten duller as I've aged. I miss that healthy glow I used to have.",
      "I'm starting to see fine lines and want to be proactive before they become deep wrinkles.",
      "Redness and sensitivity have become my norm. I want calmer, happier skin.",
    ],
    optimist: [
      "My skin is pretty good but I want that lit-from-within glow everyone talks about!",
      "Excited to support my skin from the inside. Healthy skin is happy skin!",
      "Looking to age gracefully. Starting skin support now seems smart.",
    ],
  },
  fitness: {
    desperate: [
      "I've been stuck at the same bench press for 8 months. My plateau has plateaued. Nothing I try breaks through.",
      "I train hard 5 days a week and look the same as I did a year ago. My body just won't change anymore.",
      "My cardio endurance has actually declined despite consistent training. Something is fundamentally wrong.",
      "I've hired trainers, tried every program, optimized my diet. Still can't break through this wall.",
      "I'm getting slower and weaker despite doing everything right. It's like my body is working against me.",
      "I used to make progress every month. Now I go backward if I miss a single week. I'm losing hope.",
    ],
    skeptic: [
      "Fitness supplements are 90% marketing and 10% caffeine. Show me real performance data.",
      "I've wasted money on pre-workouts, fat burners, and muscle builders that did nothing.",
      "My results come from hard work, not pills. But I'll track my lifts and times to see if this adds anything.",
      "The supplement industry is built on hype. I need peer-reviewed evidence before I believe anything.",
      "I've seen too many 'before and after' photos that are just lighting and angles.",
    ],
    power_user: [
      "My VO2 max has plateaued at 48 despite zone 2 training. Looking for something to push past the ceiling.",
      "I track every workout — RPE, heart rate, power output. Ready to see if this creates measurable gains.",
      "My recovery between sets and sessions is good. Looking to optimize actual performance output.",
      "I've dialed in periodization, nutrition timing, sleep. Supplementation is the remaining variable.",
    ],
    struggler: [
      "I start strong every January but lose motivation by March. Looking for something to help me stay consistent.",
      "I know what to do, I just can't seem to stick with it. Maybe this will help me show up more often.",
      "My energy for workouts is inconsistent. Some days I'm fired up, others I can barely finish my warm-up.",
      "I've been 'getting back into shape' for three years. I need something to actually make it stick.",
      "Progress is so slow it's hard to stay motivated. I need something to show that effort is paying off.",
    ],
    optimist: [
      "Already in decent shape but looking to level up! Ready to see what optimized performance feels like.",
      "I love working out and want to get even more from my sessions. Excited to try this!",
      "Training for a race and want every edge I can get. Let's go!",
    ],
  },
  hair: {
    desperate: [
      "I'm watching my hairline disappear and it's taking my confidence with it. I've tried minoxidil, finasteride, everything.",
      "My hair is falling out in clumps. The shower drain is a horror show every morning. I'm panicking.",
      "I used to have thick, beautiful hair. Now I'm styling to hide thin spots. I need this to work.",
      "I'm only 28 and already losing my hair. I can't accept this as my future.",
      "The hair loss came out of nowhere after pregnancy and never stopped. Three years later, I'm desperate.",
      "I've spent so much on treatments that don't work. This is my last attempt before I accept defeat.",
    ],
    skeptic: [
      "Hair supplements are mostly biotin marketing. I've tried them before with zero results.",
      "If there was a real solution for hair loss, everyone would know about it. I'm skeptical but trying anyway.",
      "I'll take photos every week. Either this works or it doesn't — I won't imagine results that aren't there.",
      "My dermatologist says most hair supplements are pseudoscience. But I'm running out of options.",
    ],
    power_user: [
      "I've optimized my diet, reduced stress, use red light therapy. Looking for the supplement piece.",
      "I track hair loss in my brush and shower drain. Ready to measure any changes objectively.",
      "I've researched every ingredient in hair supplements. This formulation actually makes sense to me.",
      "I take a systematic approach to hair health. Adding this to see if it fills a gap in my protocol.",
    ],
    struggler: [
      "My hair isn't falling out dramatically, but it's definitely thinner than it used to be. Time to do something.",
      "I've noticed more hair in my brush lately. Want to address it before it gets worse.",
      "My hair just doesn't have the life it used to have. It's dull and flat no matter what I do.",
      "Breakage has become a real problem. I can't grow my hair past a certain length anymore.",
    ],
    optimist: [
      "My hair is fine but I'd love more volume and shine. Ready to support it from the inside!",
      "Proactively protecting my hair before any issues start. Prevention is better than cure!",
      "Excited to see if I can get my hair even healthier. It's already good but could be great!",
    ],
  },
  immunity: {
    desperate: [
      "I catch every cold that goes around. I've been sick 8 times this year already. My immune system is broken.",
      "I can't afford to keep getting sick. I've missed so much work and my boss is losing patience.",
      "Every illness hits me harder than everyone else and takes twice as long to recover from.",
      "My kids bring home germs and I'm always the one who ends up in bed for a week. I need protection.",
      "I feel like I'm always fighting something off. There's never a week where I feel 100%.",
      "Post-COVID, my immune system has never been the same. I get sick constantly now.",
    ],
    skeptic: [
      "Immune supplements are usually just vitamin C in fancy packaging. The evidence is weak at best.",
      "You can't really 'boost' your immune system — that's not how immunology works. But I'll try this.",
      "I've tried elderberry, zinc, echinacea — still got sick just as often. Not expecting much.",
      "My doctor says a healthy lifestyle is the only real immune support. I'll track my sick days to compare.",
    ],
    power_user: [
      "I've optimized sleep, diet, and exercise for immune health. Looking for supplemental support during high-risk seasons.",
      "I track my sick days and symptom severity. Ready to see if this changes my patterns.",
      "I already take vitamin D and zinc. Looking for something more comprehensive.",
      "My health stack is solid but I still get 2-3 colds per year. Want to reduce that number.",
    ],
    struggler: [
      "I get sick more often than most people and I'm tired of it. Time to be proactive.",
      "Every change in season brings a cold. I want to break that pattern.",
      "Recovery from illness takes me forever. I want to bounce back faster.",
      "I'm not constantly sick, but I feel like I'm always on the verge of something.",
    ],
    optimist: [
      "Flu season is coming and I want to be prepared! Ready to support my immune system.",
      "I rarely get sick but I'd love to keep it that way. Prevention mode activated!",
      "Excited to give my immune system extra support. Staying healthy is the goal!",
    ],
  },
  resilience: {
    desperate: [
      "Every small setback feels catastrophic. I used to be strong, now I crumble at the slightest pressure.",
      "I can't handle stress like I used to. Things that never bothered me now send me spiraling.",
      "My stress tolerance is at an all-time low. I cry in my car after work most days.",
      "I used to thrive under pressure. Now pressure just breaks me. I need to get my old self back.",
      "Life keeps throwing curveballs and I have nothing left to catch them with. I'm depleted.",
      "My resilience is completely gone after burnout. I need to rebuild from the ground up.",
    ],
    skeptic: [
      "Resilience is personality and life experience, not something you can put in a pill.",
      "I've done therapy and learned coping skills. A supplement can't replace that work.",
      "I'm skeptical that anything external can change my internal stress response.",
      "If building resilience were easy, everyone would be resilient. I'll try this but expect nothing.",
    ],
    power_user: [
      "I meditate daily, journal, exercise, and still struggle with stress resilience. Looking for an edge.",
      "I track my stress levels and HRV. I can see when I'm depleted. Want to maintain higher baseline.",
      "I've built good habits but my stress capacity still feels limited. Time to try the supplement angle.",
      "My recovery from stressors is slow. I want faster bounce-back between challenges.",
    ],
    struggler: [
      "I recover from stress, but it takes me longer than it should. I want more elasticity.",
      "Small things knock me off balance more than they should. I want to be more stable.",
      "I handle big crises okay, but the daily grind wears me down. Need more durability.",
      "I used to bounce back quickly. Now I need days to recover from a hard week.",
    ],
    optimist: [
      "I handle stress pretty well but I'd love to be even more unshakeable!",
      "Building mental toughness is a practice. Excited to add this to my toolkit!",
      "Life is full of challenges. I want to meet them with strength and grace!",
    ],
  },
  libido: {
    desperate: [
      "My desire has completely vanished. I can't remember the last time I felt attracted to anyone. It's affecting my marriage.",
      "I used to have a healthy drive. Now it's like that part of me shut off. I've tried everything my doctor suggested.",
      "The disconnect is destroying my relationship. My partner feels rejected and I feel broken.",
      "I'm too young to have no desire. I'm in my 30s and feel like I'm 80. Something is wrong.",
      "Hormones checked, thyroid checked, everything's 'fine' — but I have zero interest. I'm desperate for answers.",
      "My libido disappeared after having kids and never came back. It's been 4 years now.",
    ],
    skeptic: [
      "Libido supplements are usually just marketing to desperate people. I'll track my experience carefully.",
      "I've tried maca, tribulus, all the traditional aphrodisiacs. Nothing made a real difference.",
      "This is a complex issue — hormones, psychology, relationship dynamics. A pill can't fix all that.",
      "My doctor says libido supplements don't work. But I'm willing to give it a try.",
    ],
    power_user: [
      "I've optimized hormones, sleep, stress, exercise. Looking for the final piece of the puzzle.",
      "I track my energy and mood. Want to see if this correlates with any changes.",
      "I've addressed all the lifestyle factors. Time to try targeted supplementation.",
      "My baseline is okay but I want to feel more like my younger self. Optimization mindset.",
    ],
    struggler: [
      "My desire has faded gradually over the years. I barely noticed until my partner pointed it out.",
      "I'm interested in theory but can't seem to get motivated in practice. It's frustrating.",
      "Stress has killed my drive. When I'm relaxed on vacation, everything works fine.",
      "I want to want to, if that makes sense. The spirit is willing but nothing else is.",
    ],
    optimist: [
      "Things are good but could be better! Ready to reignite the spark.",
      "I believe in maintaining all aspects of health. This is part of overall wellness!",
      "Excited to feel more vibrant and connected. Let's go!",
    ],
  },
  satiety: {
    desperate: [
      "I'm hungry ALL the time. No matter how much I eat, I want more. It's destroying my weight loss efforts.",
      "The cravings are uncontrollable. I can't stop thinking about food. It's like an obsession.",
      "I've tried every diet but I can't stick to any of them because I'm constantly starving.",
      "I eat a full meal and I'm hungry an hour later. Something is broken with my hunger signals.",
      "Willpower isn't the issue — I literally cannot feel full. My body is working against me.",
      "The late-night cravings are destroying me. I can be perfect all day and lose control at 10pm.",
    ],
    skeptic: [
      "Appetite suppressants usually have terrible side effects or don't actually work.",
      "My hunger is driven by hormones and habits, not something a supplement can fix.",
      "I've tried fiber supplements, protein shakes — still hungry. Not expecting miracles.",
      "If controlling appetite were easy, no one would be overweight. I'm skeptical.",
    ],
    power_user: [
      "I eat high protein, plenty of fiber, drink water before meals. Looking for additional satiety support.",
      "I track my hunger levels throughout the day. Ready to see if this smooths out the pattern.",
      "I've optimized meal timing and composition. Supplementation is the next lever to try.",
      "My blood sugar is stable, my meals are balanced. Want to eliminate the remaining cravings.",
    ],
    struggler: [
      "I snack more than I should. Not out of hunger exactly, but the urge is always there.",
      "I eat reasonable portions but never feel satisfied. Like something is missing.",
      "The urge to eat hits hardest in the afternoon. If I could just get through 2-5pm, I'd be fine.",
      "I finish meals and immediately start thinking about the next one. I want food to stop dominating my thoughts.",
    ],
    optimist: [
      "I eat pretty well but would love to feel more satisfied with smaller portions!",
      "Excited to feel full and content after meals. No more grazing!",
      "Looking to support my body's natural fullness signals. Let's do this!",
    ],
  },
  default: {
    desperate: [
      "I've tried everything and nothing has worked. This is my last hope.",
      "My quality of life has declined so much. I need something to change.",
    ],
    skeptic: [
      "I'm skeptical but willing to give it a fair try and track the results.",
      "Not expecting miracles, but open to seeing if it helps.",
    ],
    power_user: [
      "I've optimized the basics. Looking for the next level of improvement.",
      "I track everything and want to see measurable improvement.",
    ],
    struggler: [
      "I've been dealing with this for a while and finally decided to try something.",
      "It's not terrible, but I know I could feel better.",
    ],
    optimist: [
      "Excited to see what this can do for me!",
      "Ready for positive changes in my wellness journey.",
    ],
  },
};

// ============================================================================
// CATEGORY-SPECIFIC HOPED OUTCOMES
// What participants hope to achieve, phrased in their own aspirational words.
// ============================================================================

export const CATEGORY_HOPED_OUTCOMES: Record<string, string[]> = {
  sleep: [
    "Finally fall asleep within 15 minutes of lying down",
    "Sleep through the night without waking at 3am",
    "Wake up actually feeling refreshed for once",
    "Stop the racing thoughts when my head hits the pillow",
    "Get my deep sleep percentage above 20%",
    "Not need sleep aids to fall asleep anymore",
    "Have consistent sleep, not good nights and bad nights",
    "Feel rested enough to exercise in the morning again",
  ],
  stress: [
    "Feel calm even when work gets hectic",
    "Stop carrying work stress home to my family",
    "Release the constant tension in my shoulders and jaw",
    "Handle pressure without feeling overwhelmed",
    "Enjoy evenings instead of ruminating about tomorrow",
    "Have a lower baseline anxiety level",
    "Not feel on edge all the time",
    "Actually relax when I try to relax",
  ],
  energy: [
    "Have steady energy from morning to evening",
    "Eliminate the afternoon crash completely",
    "Not need coffee just to function",
    "Have enough energy for my family after work",
    "Feel alert and present throughout the day",
    "Wake up energized instead of hitting snooze",
    "Stop feeling like I'm running on fumes",
    "Have the energy to exercise again",
  ],
  focus: [
    "Finish tasks without my mind wandering",
    "Stay focused in long meetings",
    "Read a whole chapter without losing my place",
    "Clear the mental fog that clouds my thinking",
    "Make decisions quickly and confidently",
    "Be fully present in conversations",
    "Complete deep work for hours without distraction",
    "Feel mentally sharp again",
  ],
  recovery: [
    "Recover overnight instead of over days",
    "Train hard without being sore for a week",
    "See my HRV improve consistently",
    "Maintain performance across a full training block",
    "Wake up ready to train again",
    "Not be the limiting factor in my progress",
    "Feel as recovered as my younger self",
    "Hit PRs without extended recovery periods",
  ],
  gut: [
    "Eat a meal without bloating afterwards",
    "Not have to plan my life around bathroom access",
    "Enjoy food again without fear of discomfort",
    "Wake up with a flat stomach instead of bloated",
    "Have regular, predictable digestion",
    "Stop the cramping and pain after eating",
    "Feel comfortable in my clothes all day",
    "Eat out at restaurants without anxiety",
    "Have more food freedom without consequences",
    "Trust my gut to handle normal foods",
  ],
  weight: [
    "Lose weight and actually keep it off this time",
    "Fit back into my favorite clothes",
    "Stop the constant cycle of losing and regaining",
    "Feel comfortable and confident in my body",
    "Have sustainable results, not quick-fix disappointment",
    "Break through this stubborn plateau",
    "Not obsess about food and calories constantly",
    "Have energy to exercise without feeling depleted",
    "See the scale move in the right direction consistently",
    "Build a healthy relationship with my body",
  ],
  anxiety: [
    "Feel calm in situations that usually trigger me",
    "Stop the racing thoughts that keep me up at night",
    "Go through a day without that knot in my stomach",
    "Attend social events without dreading them for days",
    "Handle stress without spiraling into worst-case scenarios",
    "Feel grounded and present instead of constantly worried",
    "Reduce my dependence on anxiety medication",
    "Have confidence that I can handle whatever comes",
    "Stop the physical symptoms — the tight chest, the racing heart",
    "Enjoy life instead of just surviving it",
  ],
  mood: [
    "Feel genuinely happy, not just 'fine'",
    "Have consistent, stable moods throughout the day",
    "Wake up actually looking forward to the day",
    "Stop the irritability that's hurting my relationships",
    "Feel like myself again — positive and engaged",
    "Have energy and motivation for things I used to enjoy",
    "Not feel like I'm just going through the motions",
    "Experience joy in small things again",
    "Feel emotionally resilient when things go wrong",
    "Have more good days than bad days",
  ],
  pain: [
    "Have pain-free days again",
    "Wake up without morning stiffness",
    "Be able to play with my kids without paying for it later",
    "Reduce my dependence on pain medication",
    "Sleep through the night without pain waking me up",
    "Get back to activities I've given up",
    "Have consistent comfort, not good days and bad days",
    "Feel like myself again, not defined by pain",
    "Exercise without fear of flare-ups",
    "Actually enjoy life instead of just enduring it",
  ],
  skin: [
    "Have clear, glowing skin I'm proud of",
    "Wake up without new breakouts",
    "Feel confident going makeup-free",
    "Stop hiding behind filters in photos",
    "Have even skin tone without redness",
    "Look as young as I feel",
    "Stop the cycle of breakouts and scarring",
    "Have skin that doesn't need constant attention",
    "Feel comfortable in my own skin — literally",
    "Get compliments on my complexion again",
  ],
  fitness: [
    "Break through this plateau finally",
    "Set a new personal record",
    "Have energy for longer, harder workouts",
    "See visible progress in the mirror",
    "Train consistently without burnout",
    "Perform at my potential, not below it",
    "Recover faster between sessions",
    "Have the endurance I used to have",
    "Feel strong and capable again",
    "Reach the fitness level I know I'm capable of",
  ],
  hair: [
    "Stop the shedding and thinning",
    "Have thick, full hair again",
    "Feel confident without hats or styling tricks",
    "Stop seeing my scalp through my hair",
    "Grow my hair longer without breakage",
    "Have healthy, shiny hair",
    "Stop dreading looking in the mirror",
    "Feel like my hair represents who I am",
    "Not worry about hair loss anymore",
    "Have hair that makes me feel confident",
  ],
  immunity: [
    "Go through flu season without getting sick",
    "Stop catching every bug that goes around",
    "Recover faster when I do get sick",
    "Feel confident my body can fight things off",
    "Stop missing work due to illness",
    "Have reliable, strong immunity",
    "Not be the first one sick in my household",
    "Feel healthy and resilient year-round",
    "Stop the cycle of illness-recovery-illness",
    "Trust my immune system to protect me",
  ],
  resilience: [
    "Handle stress without falling apart",
    "Bounce back faster from setbacks",
    "Stay calm under pressure",
    "Feel unshakeable in difficult situations",
    "Maintain equilibrium through life's challenges",
    "Not let small things derail my whole day",
    "Have the mental toughness I used to have",
    "Face challenges with confidence, not dread",
    "Recover from hard weeks without needing days off",
    "Feel like I can handle whatever life throws at me",
  ],
  libido: [
    "Feel desire again like I used to",
    "Have a healthy, active intimate life",
    "Connect with my partner physically again",
    "Feel attractive and interested",
    "Not have intimacy feel like a chore",
    "Have spontaneous desire, not just responsive",
    "Feel like my whole self, not missing a part",
    "Enjoy this aspect of life again",
    "Stop feeling broken in this area",
    "Have energy and interest for intimacy",
  ],
  satiety: [
    "Feel satisfied after meals",
    "Stop thinking about food constantly",
    "Control cravings instead of them controlling me",
    "Eat normal portions and feel full",
    "Stop the late-night snacking",
    "Have a normal relationship with food",
    "Trust my hunger and fullness signals",
    "Not feel like I'm always fighting my appetite",
    "Eat to live, not live to eat",
    "Finally feel in control around food",
  ],
  default: [
    "Feel noticeably better day to day",
    "See measurable improvement in how I feel",
    "Have evidence that something is actually working",
    "Feel more like my best self",
    "Improve my overall quality of life",
  ],
};

// Category-specific motivation statements
export const CATEGORY_MOTIVATIONS: Record<string, string[]> = {
  sleep: [
    "I've been struggling to fall asleep for months",
    "Want to wake up feeling more refreshed",
    "Tired of relying on sleep aids",
    "My sleep tracker shows poor sleep quality",
    "Looking for natural ways to improve sleep",
    "I wake up multiple times every night and can't get back to sleep",
    "My partner says I toss and turn all night — I need a real fix",
    "I average less than 5 hours of deep sleep a week according to my Oura Ring",
    "The racing thoughts at bedtime have gotten worse over the past year",
    "I want to stop needing melatonin every single night",
    "My sleep used to be great — something changed after turning 40",
    "I've tried weighted blankets, white noise, blue light glasses — nothing sticks",
    "My job requires early mornings and I can't keep dragging myself out of bed",
    "Hoping to improve my HRV through better sleep quality",
    "I fall asleep fine but wake up at 3am every single night",
    "Looking to optimize my sleep stack — this is the missing piece I think",
    "My recovery scores on Whoop have been tanking and I'm sure it's sleep-related",
    "Stress from work carries into nighttime and ruins my sleep",
    "I feel like I haven't had a truly restful night in over a year",
    "My doctor said my sleep efficiency is below 80% — trying to fix that naturally",
    "Training for a marathon and sleep is the bottleneck in my recovery",
    "I'm a light sleeper and need something to help me stay in deep sleep longer",
    "My kids finally sleep through the night — now I need to learn how to again",
    "I want to see if improving sleep helps my chronic brain fog",
    "Tried prescription sleep meds and hated the side effects — want something natural",
    "My Fitbit shows I barely get any REM sleep and I want to change that",
    "I need 8 hours but I'm only getting 5.5 — and I feel every missing minute",
    "Looking to break the cycle of poor sleep → caffeine → poor sleep",
    "Heard about this from a friend who said it fixed her sleep in two weeks",
    "I just want one full week of consistent, restful sleep — is that too much to ask?",
  ],
  stress: [
    "Work stress has been overwhelming lately",
    "Looking for better ways to manage anxiety",
    "Want to feel calmer throughout the day",
    "Need help with daily stress management",
    "Trying to reduce tension and worry",
  ],
  energy: [
    "Experiencing afternoon energy crashes",
    "Want consistent energy throughout the day",
    "Tired of feeling fatigued all the time",
    "Looking for natural energy solutions",
    "Need more stamina for daily activities",
  ],
  focus: [
    "Difficulty concentrating at work",
    "Mind wanders during important tasks",
    "Want better mental clarity",
    "Looking to improve productivity",
    "Need help staying focused longer",
  ],
  recovery: [
    "Muscles feel sore after workouts",
    "Takes too long to recover from exercise",
    "Want to improve my HRV scores",
    "Looking for faster post-workout recovery",
    "Need better athletic performance",
  ],
  gut: [
    "I'm bloated after almost every meal — doesn't matter what I eat",
    "IBS symptoms have been controlling my life for years",
    "My digestion has gotten worse since hitting my 40s",
    "I've tried elimination diets and nothing seems to help consistently",
    "The cramping and discomfort is affecting my quality of life",
    "I can't eat out anymore without worrying about my stomach",
    "My gut issues started after a round of antibiotics and never resolved",
    "I'm tired of planning everything around bathroom access",
    "My doctor says my tests are normal but I'm clearly not normal",
    "Probiotics haven't worked — hoping this is different",
    "The bloating is so bad I look pregnant by evening",
    "I want to enjoy food again without dreading the consequences",
    "My gut affects everything — my energy, my mood, my sleep",
    "I've accepted digestive issues as my normal but I don't want to anymore",
    "Food sensitivities keep multiplying — I can barely eat anything now",
  ],
  weight: [
    "I've been stuck at the same weight for six months despite diet and exercise",
    "The pandemic weight gain has refused to come off",
    "My metabolism has completely changed since turning 40",
    "I eat healthy but the scale won't budge — something isn't working",
    "I've lost the same weight multiple times and it always comes back",
    "Looking for sustainable weight management, not another crash diet",
    "My energy is too low to exercise consistently",
    "I need help with the cravings that derail every diet attempt",
    "Weight is affecting my joints and I need to take action",
    "My doctor wants me to lose weight but nothing I try works long-term",
    "I've tried keto, paleo, intermittent fasting — none stuck",
    "I want to feel comfortable in my body again",
    "Stress eating has become a serious problem",
    "My weight has slowly crept up year after year",
    "I'm ready to make a change but I need support to stick with it",
  ],
  anxiety: [
    "My anxiety has gotten worse over the past year",
    "Work stress is triggering constant worry and tension",
    "I've started having anxiety attacks out of nowhere",
    "The anxious thoughts won't stop, especially at night",
    "Social situations have become increasingly stressful",
    "I'm tired of feeling on edge all the time",
    "My anxiety is affecting my sleep and my relationships",
    "I want to manage anxiety without increasing my medication",
    "The physical symptoms — racing heart, tight chest — are scary",
    "I've tried meditation apps but I can't seem to stick with them",
    "My worrying is excessive and I know it, but I can't stop",
    "I want to feel calm and grounded more often",
    "Anxiety runs in my family and I'm trying to get ahead of it",
    "The news and world events have made my anxiety skyrocket",
    "I need something to help me handle stressful situations better",
  ],
  mood: [
    "I've been in a low mood for months with no clear reason",
    "My mood swings are affecting my relationships",
    "I used to be positive and energetic — I don't know what happened",
    "The winter months always hit my mood hard",
    "I'm irritable and short-tempered more often than I'd like",
    "I don't feel depressed exactly, just flat and unmotivated",
    "Looking for natural ways to support my mood",
    "I want to feel more emotionally balanced day to day",
    "My motivation has completely disappeared",
    "Small things that never bothered me now set me off",
    "I want to actually enjoy life instead of just getting through it",
    "The afternoon slump affects my mood, not just my energy",
    "I've noticed mood changes since my hormones shifted",
    "I want to be a more positive presence for my family",
    "Stress has flattened my usual optimism",
  ],
  pain: [
    "Chronic back pain has been my constant companion for years",
    "My joints ache every morning — it takes an hour to loosen up",
    "I've tried physical therapy, injections, even surgery — still in pain",
    "The pain is limiting what I can do with my life",
    "I'm tired of taking pain medication every day",
    "Fibromyalgia has robbed me of my energy and joy",
    "My headaches have become more frequent and severe",
    "I can't exercise like I used to because of the pain",
    "The pain affects my sleep, which makes everything worse",
    "I've spent thousands on treatments with minimal results",
    "I'm not ready to accept that this is just my life now",
    "The pain is affecting my mood and my relationships",
    "I've been managing chronic pain for over a decade",
    "Looking for something to take the edge off without side effects",
    "I want to be active again without paying for it the next day",
  ],
  skin: [
    "Adult acne is ruining my confidence at work",
    "My skin has gotten worse since I turned 30",
    "I've tried every prescription and over-the-counter treatment",
    "Rosacea makes me look flushed all the time",
    "My skin is so sensitive that most products irritate it",
    "I want to look good without wearing makeup every day",
    "The texture of my skin has changed and I hate it",
    "I'm starting to see aging signs I'm not ready for",
    "My skin looks tired and dull no matter what I do",
    "Hormonal breakouts are predictable and frustrating",
    "I've accepted bad skin for too long — time for a change",
    "My skincare routine isn't working anymore",
    "I want that healthy, glowing skin everyone talks about",
    "Dark spots and uneven tone make me self-conscious",
    "I'm investing in my skin for the long term",
  ],
  fitness: [
    "I've hit a plateau and can't seem to break through",
    "My performance has stagnated despite consistent training",
    "I want to take my fitness to the next level",
    "Training for a competition and need every advantage",
    "My energy in the gym isn't what it used to be",
    "I'm working out but not seeing results anymore",
    "Looking to improve my endurance for longer workouts",
    "I want to build more muscle but seem to have maxed out",
    "My recovery between workouts is too slow",
    "I need help staying consistent with my training",
    "I'm losing fitness gains faster than I can build them",
    "Looking for something to help me push through tough workouts",
    "I want to perform at my peak, not just average",
    "My workout motivation has been lacking lately",
    "I know I'm capable of more but something is holding me back",
  ],
  hair: [
    "I'm noticing more hair in my brush than ever before",
    "My hairline is receding and it's affecting my confidence",
    "Postpartum hair loss never fully recovered",
    "My hair has become thin and wispy over the past few years",
    "I want thicker, fuller hair like I used to have",
    "Breakage and damage have made my hair impossible to grow",
    "My hair is dull and lifeless no matter what products I use",
    "I'm too young to be dealing with hair loss",
    "My hair has changed since menopause and I want it back",
    "I've tried everything topical — time to work from the inside",
    "Looking for something to support healthy hair growth",
    "My hairdresser has noticed my hair getting thinner",
    "I want to feel confident about my hair again",
    "The shedding has gotten worse over the past year",
    "I'm proactively supporting my hair before it becomes a bigger issue",
  ],
  immunity: [
    "I seem to catch every cold and flu that goes around",
    "My immune system has been weak since I had COVID",
    "I'm tired of being sick multiple times a year",
    "I want to stay healthy during cold and flu season",
    "My kids bring home germs and I always catch them",
    "I take forever to recover from illnesses",
    "Looking for proactive immune support",
    "I can't afford to be sick with my work schedule",
    "My immune system needs a boost heading into winter",
    "I've been getting sick more often as I've gotten older",
    "I want to feel protected and resilient",
    "Every time I travel, I come back sick",
    "I'm looking to support my body's natural defenses",
    "Stress has weakened my immune system",
    "I want to be the healthy one in my household for once",
  ],
  resilience: [
    "I don't bounce back from stress like I used to",
    "Small setbacks completely derail me now",
    "I feel mentally fragile and I used to be tough",
    "Work pressure is breaking me down",
    "I need to build back my stress tolerance",
    "Life changes have depleted my reserves",
    "I want to be unshakeable again",
    "My emotional bandwidth is at an all-time low",
    "I used to thrive under pressure — now I crumble",
    "Looking for support to handle life's challenges better",
    "Burnout has left me with no resilience",
    "I need more mental stamina to get through tough weeks",
    "I want to feel strong and capable again",
    "The daily grind wears me down too quickly",
    "I'm building back from a difficult period",
  ],
  libido: [
    "My desire has dropped significantly over the past year",
    "I miss feeling interested in intimacy",
    "Hormonal changes have affected my libido",
    "Stress has killed my drive completely",
    "I want to feel connected to my partner again",
    "My libido isn't what it used to be and I want it back",
    "I feel like a part of me is missing",
    "Antidepressants have affected this area of my life",
    "I'm not interested but I want to be interested",
    "My relationship is suffering because of this",
    "I want to feel vibrant and alive again",
    "Age-related changes have affected my desire",
    "Looking for natural support in this area",
    "I used to have a healthy drive — what happened?",
    "I want to feel like my whole self again",
  ],
  satiety: [
    "I'm hungry again an hour after eating a full meal",
    "The cravings are constant and overwhelming",
    "I can't seem to feel full no matter how much I eat",
    "Late-night snacking is sabotaging my health goals",
    "My appetite is out of control",
    "I think about food all the time — it's exhausting",
    "Portion control is impossible when I'm always hungry",
    "I eat well but still want more",
    "The hunger makes every diet impossible to stick to",
    "I need help feeling satisfied after meals",
    "My willpower runs out when I'm constantly hungry",
    "I want to eat to live, not live to eat",
    "The afternoon is when cravings hit hardest",
    "I eat for reasons other than hunger and want to stop",
    "I need support managing my appetite naturally",
  ],
  default: [
    "Looking to improve my overall wellness",
    "Heard great things about this product",
    "Want to feel better day to day",
    "Ready to try something new",
    "Hoping for positive changes",
  ],
};

// Category-specific hoped results
export const CATEGORY_HOPED_RESULTS: Record<string, string[]> = {
  sleep: [
    "Fall asleep faster and stay asleep",
    "Wake up feeling energized",
    "Better deep sleep scores on my tracker",
    "Less tossing and turning",
    "Feel rested in the morning",
  ],
  stress: [
    "Feel calmer and more relaxed",
    "Handle stressful situations better",
    "Lower overall anxiety levels",
    "Better HRV and recovery scores",
    "More peace of mind",
  ],
  energy: [
    "Steady energy all day long",
    "No more afternoon crashes",
    "Feel more alert and awake",
    "Better morning energy",
    "Increased daily productivity",
  ],
  focus: [
    "Better concentration at work",
    "Clearer thinking and decision making",
    "Less mental fog",
    "Improved memory and recall",
    "Sustained attention on tasks",
  ],
  recovery: [
    "Faster muscle recovery",
    "Improved HRV scores",
    "Less soreness after training",
    "Better athletic performance",
    "More energy for workouts",
  ],
  gut: [
    "Significantly less bloating after meals",
    "More regular and predictable digestion",
    "Reduced cramping and abdominal discomfort",
    "Ability to eat more foods without reactions",
    "Feeling comfortable in my body throughout the day",
    "Less anxiety around eating and food choices",
    "Improved energy from better nutrient absorption",
    "Normal bowel movements consistently",
  ],
  weight: [
    "Steady, sustainable weight loss",
    "Reduced cravings and better appetite control",
    "More energy for exercise and daily activities",
    "Clothes fitting better and more comfortably",
    "Breaking through weight loss plateaus",
    "Better relationship with food and eating",
    "Improved body composition and muscle retention",
    "Consistent progress without the yo-yo effect",
  ],
  anxiety: [
    "Feeling calmer in stressful situations",
    "Fewer racing thoughts and worries",
    "Better sleep without anxious thoughts",
    "More confidence in social situations",
    "Reduced physical anxiety symptoms",
    "Feeling more grounded and present",
    "Better ability to handle unexpected stress",
    "Less overall tension and nervousness",
  ],
  mood: [
    "More consistently positive mood",
    "Feeling genuinely happy more often",
    "Less irritability and mood swings",
    "Better emotional resilience",
    "Increased motivation and engagement",
    "Feeling like myself again",
    "More joy in daily activities",
    "Stable moods throughout the day",
  ],
  pain: [
    "Noticeable reduction in pain levels",
    "More pain-free days overall",
    "Better mobility and flexibility",
    "Less reliance on pain medication",
    "Improved sleep due to less pain",
    "Ability to do activities I've avoided",
    "Reduced morning stiffness",
    "Better quality of life overall",
  ],
  skin: [
    "Clearer, more radiant skin",
    "Fewer breakouts and blemishes",
    "More even skin tone",
    "Reduced redness and inflammation",
    "Healthier, more hydrated skin",
    "Visible improvement in skin texture",
    "More confidence going makeup-free",
    "Compliments on my complexion",
  ],
  fitness: [
    "Breaking through current plateaus",
    "Improved strength or endurance",
    "Better performance in workouts",
    "More consistent training results",
    "Faster recovery between sessions",
    "Increased energy during exercise",
    "Visible changes in body composition",
    "New personal records",
  ],
  hair: [
    "Less hair shedding and loss",
    "Thicker, fuller-looking hair",
    "Stronger hair with less breakage",
    "Improved hair texture and shine",
    "Healthier hair growth patterns",
    "More confidence in my hair",
    "Visible improvement in hair density",
    "Hair that looks and feels healthier",
  ],
  immunity: [
    "Getting sick less often",
    "Faster recovery when I do get sick",
    "Stronger immune response overall",
    "Making it through flu season healthy",
    "More consistent health year-round",
    "Feeling protected and resilient",
    "Fewer missed days due to illness",
    "Confidence in my body's defenses",
  ],
  resilience: [
    "Better handling of daily stress",
    "Faster recovery from setbacks",
    "More emotional stability",
    "Increased stress tolerance",
    "Feeling more mentally tough",
    "Better able to cope with challenges",
    "More consistent emotional state",
    "Feeling strong and capable",
  ],
  libido: [
    "Increased desire and interest",
    "More energy for intimacy",
    "Better connection with partner",
    "Feeling more like myself",
    "Improved overall vitality",
    "More spontaneous interest",
    "Better mood and confidence",
    "Healthier intimate life overall",
  ],
  satiety: [
    "Feeling satisfied after meals",
    "Fewer cravings throughout the day",
    "Better portion control naturally",
    "Less snacking between meals",
    "More control over appetite",
    "Thinking about food less often",
    "Eating normal amounts and feeling full",
    "Breaking the cycle of overeating",
  ],
  default: [
    "Overall improvement in how I feel",
    "Better daily energy and mood",
    "Noticeable positive changes",
    "Improved wellbeing",
    "Feel healthier overall",
  ],
};

// Category-specific hero symptom questions and responses
export const CATEGORY_HERO_SYMPTOMS: Record<string, { question: string; responses: string[] }> = {
  sleep: {
    question: "What's your biggest challenge with sleep right now?",
    responses: [
      "I can't fall asleep — my mind races the moment my head hits the pillow",
      "I wake up at 3am every night and can't get back to sleep",
      "I sleep 8 hours but wake up exhausted like I didn't sleep at all",
      "Racing thoughts keep me up until 2-3am most nights",
      "I'm dependent on sleep aids and want to stop",
      "Light sleep all night — I never feel like I hit deep sleep",
      "Takes me over an hour to fall asleep, no matter how tired I am",
      "I wake up 3-4 times a night and each time it takes 20+ minutes to fall back asleep",
      "My sleep schedule is completely inconsistent — I have no rhythm",
      "I get plenty of sleep time but my Oura shows barely any deep sleep",
      "Work anxiety follows me to bed and I literally cannot turn off my brain",
      "I've tried melatonin, magnesium, valerian — nothing gives me consistent relief",
      "My sleep got worse after having kids and never recovered even though they sleep through now",
      "I feel wired at bedtime but exhausted all day — my circadian rhythm is broken",
      "Hot flashes and night sweats wake me up multiple times",
      "I snore badly according to my partner, and I wake up with headaches",
      "Anxiety medication helps me fall asleep but I wake up groggy and foggy",
      "I haven't slept through the night in over a year — it's affecting my work performance",
      "My deep sleep percentage is 8% according to my watch — should be closer to 20%",
      "I grind my teeth at night from stress and wake up with jaw pain",
      "I fall asleep on the couch but can't fall asleep in bed — it's psychological at this point",
      "Sunday night insomnia ruins my whole Monday. It's like clockwork every week.",
      "Travel for work has destroyed whatever sleep habits I had",
      "I wake up too early (5am) no matter when I go to bed and can't fall back asleep",
      "The quality of my sleep is so poor that 8 hours feels like 4",
    ],
  },
  stress: {
    question: "What's your biggest source of stress right now?",
    responses: [
      "Work pressure is constant and overwhelming",
      "I can't stop worrying about everything, even small things",
      "Physical tension - my shoulders and jaw are always tight",
      "My mind never stops racing, even when I try to relax",
      "Anxiety spikes at random times throughout the day",
      "I feel on edge constantly, waiting for the next crisis",
    ],
  },
  energy: {
    question: "When is your energy lowest and how does it affect you?",
    responses: [
      "2-3pm crash every single day - I can barely keep my eyes open",
      "I'm exhausted from the moment I wake up until I go to bed",
      "My energy is unpredictable - some days I crash hard, others I'm okay",
      "I need caffeine just to function, and even that's not enough anymore",
      "By dinner time I have nothing left for my family",
      "Brain fog and fatigue make it hard to focus on anything",
    ],
  },
  focus: {
    question: "How does your lack of focus impact your daily life?",
    responses: [
      "I can't concentrate on work tasks - constantly getting distracted",
      "My mind wanders during important conversations and meetings",
      "I start tasks but can't finish them - my attention just drifts",
      "Reading has become impossible - I re-read the same paragraph over and over",
      "I'm making mistakes at work I never used to make",
      "Brain fog makes even simple decisions feel overwhelming",
    ],
  },
  recovery: {
    question: "What recovery challenges are you experiencing?",
    responses: [
      "My muscles are sore for days after workouts",
      "I used to recover quickly but now everything takes longer",
      "My HRV is consistently low despite sleeping enough",
      "I feel depleted even after rest days",
      "Performance is declining even though I'm training consistently",
      "Takes me 3-4 days to feel ready for another hard workout",
    ],
  },
  gut: {
    question: "What's your biggest digestive challenge right now?",
    responses: [
      "I'm bloated after every meal — my stomach looks pregnant by evening",
      "Unpredictable bowel movements control when I can leave the house",
      "Cramping and pain after eating make me dread mealtimes",
      "I've developed sensitivities to foods I used to eat without problems",
      "Constant gas and discomfort that I can't seem to fix",
      "IBS symptoms that flare unpredictably and ruin my plans",
      "I can't eat at restaurants anymore without consequences",
      "My digestion is so slow — I feel heavy and sluggish constantly",
      "Alternating between constipation and the opposite — no middle ground",
      "Brain fog and fatigue that I'm sure is connected to my gut",
      "My stomach gurgles and makes noises constantly — it's embarrassing",
      "I've eliminated so many foods I barely know what to eat anymore",
      "Acid reflux and heartburn after most meals",
      "Nausea that comes and goes with no clear pattern",
      "My gut issues started after food poisoning and never resolved",
    ],
  },
  weight: {
    question: "What's been your biggest struggle with weight management?",
    responses: [
      "I lose weight but it always comes back — usually with extra pounds",
      "My metabolism seems broken — I eat less than others and still gain",
      "The cravings sabotage every diet I try",
      "I've hit a plateau and nothing breaks it — not even cutting more calories",
      "Emotional eating takes over when I'm stressed",
      "I don't have energy to exercise, which makes everything harder",
      "Portion control is impossible — I'm always hungry",
      "I lose motivation after a few weeks every single time",
      "My weight has crept up slowly for years and I can't reverse it",
      "I know what to do but I can't seem to stick with it",
      "Menopause/hormone changes have made weight impossible to manage",
      "I'm constantly thinking about food and my weight — it's exhausting",
      "I've tried every diet and none of them work long-term",
      "Late night snacking undoes all my good choices during the day",
      "I feel like my body is working against me no matter what I do",
    ],
  },
  anxiety: {
    question: "How does anxiety affect your daily life?",
    responses: [
      "Racing thoughts that won't stop, especially at night",
      "Physical symptoms — tight chest, racing heart, can't breathe deeply",
      "I worry about everything, even things I know are irrational",
      "Social situations make me so nervous I avoid them entirely",
      "I can't relax even when there's nothing specific to worry about",
      "Constant feeling of dread, like something bad is about to happen",
      "My anxiety keeps me up at night replaying conversations and scenarios",
      "I've started having panic attacks that come out of nowhere",
      "I'm on edge all the time — my family says I'm always tense",
      "I overthink every decision and second-guess myself constantly",
      "Work stress has spiraled into constant anxiety about everything",
      "The physical tension in my body is exhausting — shoulders, jaw, stomach",
      "I've become avoidant because anxiety makes everything feel overwhelming",
      "My mind immediately goes to worst-case scenarios",
      "I feel like I'm barely holding it together most days",
    ],
  },
  mood: {
    question: "How would you describe your mood most days?",
    responses: [
      "Flat and unmotivated — not sad exactly, just numb",
      "Irritable and short-tempered, even over small things",
      "Up and down — I never know which version of me will show up",
      "Low energy that makes it hard to enjoy anything",
      "I've lost interest in things that used to make me happy",
      "Easily overwhelmed by things I used to handle fine",
      "Anxious and negative more often than positive",
      "I feel disconnected from joy — like I'm going through the motions",
      "My mood tanks in the afternoon and doesn't recover",
      "I wake up dreading the day instead of looking forward to it",
      "Small setbacks completely derail my mood for hours or days",
      "I used to be positive and optimistic — that person is gone",
      "My mood affects everyone around me and I hate that",
      "I feel stuck in a low-grade funk that nothing seems to lift",
      "The irritability is the worst — I snap at people I love",
    ],
  },
  pain: {
    question: "What kind of pain are you dealing with?",
    responses: [
      "Chronic lower back pain that never fully goes away",
      "Joint pain in my knees and hips that limits my mobility",
      "Neck and shoulder tension that causes daily headaches",
      "Arthritis that makes mornings miserable",
      "Fibromyalgia-like pain that moves around my body",
      "Post-workout soreness that lasts days instead of hours",
      "Sciatica that shoots down my leg when I sit too long",
      "Migraines that knock me out for days at a time",
      "Plantar fasciitis that makes every step painful",
      "Wrist and hand pain from computer work",
      "Pain from an old injury that never healed right",
      "Muscle tension that I can't seem to release",
      "Nerve pain that tingles and burns",
      "Full-body aches that make me feel decades older",
      "Inflammation that flares up without warning",
    ],
  },
  skin: {
    question: "What skin concerns are you dealing with?",
    responses: [
      "Persistent adult acne that won't clear up",
      "Rosacea that makes my face constantly red and flushed",
      "Fine lines and wrinkles that appeared suddenly",
      "Extremely dry skin that no moisturizer fixes",
      "Oily skin with large pores and frequent breakouts",
      "Dark spots and uneven skin tone from sun damage",
      "Sensitive skin that reacts to almost everything",
      "Dull, tired-looking skin that lacks radiance",
      "Eczema patches that flare up and itch",
      "Hormonal breakouts that are predictable but unavoidable",
      "Under-eye circles and puffiness that won't go away",
      "Rough, textured skin that makeup can't smooth over",
      "Combination skin that's impossible to balance",
      "Premature aging signs I'm not ready for",
      "Acne scars and post-inflammatory hyperpigmentation",
    ],
  },
  fitness: {
    question: "What's holding back your fitness progress?",
    responses: [
      "I've hit a plateau and can't break through no matter what I try",
      "My strength gains have completely stalled",
      "Cardio endurance isn't improving despite consistent training",
      "Recovery takes too long between workouts",
      "I don't have the energy to push hard in my workouts",
      "I keep losing progress when I take even a short break",
      "My body composition won't change despite diet and exercise",
      "I can't seem to build muscle no matter how much protein I eat",
      "Motivation to work out has completely disappeared",
      "I start strong but can't maintain consistency",
      "My performance varies wildly from day to day",
      "I feel weaker than I did a year ago",
      "I can't increase my running pace or distance",
      "Injury risk is limiting how hard I can train",
      "I'm working out more but results have stopped",
    ],
  },
  hair: {
    question: "What hair concerns are you experiencing?",
    responses: [
      "My hair is falling out much more than normal",
      "I can see my scalp through my hair now",
      "My hairline is receding noticeably",
      "Hair has become thin and wispy over the past year",
      "Excessive shedding when I brush or shower",
      "My hair breaks off and won't grow past a certain length",
      "Hair texture has changed — it used to be thick and full",
      "Postpartum hair loss that hasn't recovered",
      "My hair is dull and lifeless no matter what products I use",
      "Thinning at the crown that I try to cover up",
      "My ponytail is half the thickness it used to be",
      "Hair loss after stress or illness that never grew back",
      "Brittle hair that snaps when I style it",
      "Premature graying combined with thinning",
      "My part has gotten wider and more visible",
    ],
  },
  immunity: {
    question: "How would you describe your immune health?",
    responses: [
      "I catch every cold and flu that goes around",
      "I get sick much more often than other people",
      "Recovery from illness takes me forever",
      "I've been getting sick more since COVID",
      "I'm always the first one sick in my household",
      "Every change of season brings a new illness",
      "I feel like I'm always fighting something off",
      "My immune system seems to have weakened as I've aged",
      "I can't afford to get sick but I always do",
      "Stress has destroyed my immune system",
      "I get recurring infections that keep coming back",
      "Every time I travel, I come home sick",
      "I never feel 100% — always a little run down",
      "My kids bring home germs and I catch everything",
      "I've had multiple illnesses in the past few months",
    ],
  },
  resilience: {
    question: "How do you typically handle stress and setbacks?",
    responses: [
      "Small setbacks completely derail me for days",
      "I crumble under pressure that I used to handle fine",
      "I recover from stress much slower than I used to",
      "I feel mentally fragile and easily overwhelmed",
      "Daily stress accumulates and I can't shake it off",
      "I don't bounce back from difficult situations anymore",
      "My stress tolerance is at an all-time low",
      "I feel emotionally depleted with no reserves left",
      "Minor inconveniences feel like major crises",
      "I used to thrive under pressure — now I fall apart",
      "I need days to recover from a single stressful event",
      "My emotional bandwidth is completely maxed out",
      "I feel like I'm always one bad day away from breaking",
      "Uncertainty and change paralyze me now",
      "I can't handle the same load I used to carry",
    ],
  },
  libido: {
    question: "How has your desire or interest changed?",
    responses: [
      "My desire has basically disappeared completely",
      "I'm interested in theory but not in practice",
      "My drive is much lower than it used to be",
      "Stress has killed any interest I had",
      "I feel disconnected from this part of myself",
      "Hormonal changes have affected my desire significantly",
      "I want to want to, but I just don't",
      "My partner has noticed and it's affecting our relationship",
      "I feel like something is missing but I can't explain it",
      "Medications have affected this area of my life",
      "I miss feeling vibrant and interested",
      "Fatigue makes intimacy feel like another chore",
      "My confidence in this area has plummeted",
      "I used to have a healthy drive — I don't know what happened",
      "This area of my life feels broken and I want to fix it",
    ],
  },
  satiety: {
    question: "How would you describe your appetite and cravings?",
    responses: [
      "I'm hungry again an hour after eating a full meal",
      "Cravings are constant and overwhelming",
      "I never feel truly satisfied after eating",
      "Late-night snacking is out of control",
      "I think about food constantly throughout the day",
      "I can't seem to stop eating once I start",
      "My hunger signals seem broken or absent",
      "I eat for emotional reasons, not hunger",
      "Portion sizes don't satisfy me anymore",
      "I graze all day because I'm never full",
      "The urge to snack hits hardest in the afternoon",
      "I eat healthy foods but still want more",
      "My appetite has increased significantly lately",
      "I feel out of control around food",
      "I'm always looking for the next thing to eat",
    ],
  },
  default: {
    question: "What's the biggest wellness challenge you're facing?",
    responses: [
      "I just don't feel like myself anymore",
      "My overall wellbeing has declined noticeably",
      "I'm not sick, but I'm definitely not thriving",
      "Something feels off and I can't pinpoint what",
      "I want to feel better but don't know where to start",
      "My quality of life isn't where it should be",
    ],
  },
};

// Category-specific failed alternatives
export const CATEGORY_FAILED_ALTERNATIVES: Record<string, string[]> = {
  sleep: [
    "Melatonin",
    "Prescription sleep aids",
    "Sleep apps",
    "CBT-i",
    "Weighted blanket",
    "Blue light glasses",
    "Magnesium",
    "Lavender",
  ],
  stress: [
    "Meditation apps",
    "Therapy/counseling",
    "Breathing exercises",
    "Yoga",
    "CBD",
    "Prescription anxiety meds",
    "Journaling",
    "Exercise",
  ],
  energy: [
    "Coffee/caffeine",
    "Energy drinks",
    "B vitamins",
    "Iron supplements",
    "Napping",
    "Exercise",
    "Better sleep",
    "Reducing sugar",
  ],
  focus: [
    "Caffeine",
    "Nootropics",
    "Meditation",
    "Pomodoro technique",
    "Focus apps",
    "Prescription stimulants",
    "Brain games",
    "Eliminating distractions",
  ],
  recovery: [
    "Protein supplements",
    "Foam rolling",
    "Ice baths",
    "Compression",
    "Sleep optimization",
    "Massage",
    "BCAAs",
    "Electrolytes",
  ],
  gut: [
    "Probiotics",
    "Elimination diets",
    "Low FODMAP diet",
    "Digestive enzymes",
    "Fiber supplements",
    "Peppermint oil",
    "Apple cider vinegar",
    "Prescription medications",
    "Gluten-free diet",
    "Dairy-free diet",
    "Bone broth",
    "L-glutamine",
  ],
  weight: [
    "Keto diet",
    "Intermittent fasting",
    "Calorie counting apps",
    "Weight Watchers",
    "Paleo diet",
    "Meal replacement shakes",
    "Gym membership",
    "Personal trainer",
    "Prescription weight loss meds",
    "Low-carb diet",
    "Mediterranean diet",
    "Appetite suppressants",
  ],
  anxiety: [
    "Meditation apps",
    "Breathing exercises",
    "Therapy/counseling",
    "Prescription anti-anxiety medication",
    "CBD products",
    "Exercise",
    "Yoga",
    "Journaling",
    "Ashwagandha",
    "Magnesium",
    "Chamomile tea",
    "Cutting caffeine",
  ],
  mood: [
    "Exercise",
    "Therapy",
    "Antidepressants",
    "St. John's Wort",
    "SAM-e",
    "Vitamin D",
    "Light therapy",
    "Meditation",
    "Journaling",
    "Social activities",
    "Better sleep",
    "Omega-3 supplements",
  ],
  pain: [
    "Over-the-counter pain relievers",
    "Prescription pain medication",
    "Physical therapy",
    "Chiropractic care",
    "Acupuncture",
    "Massage therapy",
    "Heat/ice therapy",
    "TENS units",
    "Cortisone injections",
    "Topical creams and patches",
    "Yoga/stretching",
    "CBD products",
  ],
  skin: [
    "Prescription retinoids",
    "Antibiotics (topical and oral)",
    "Accutane/isotretinoin",
    "Chemical peels",
    "Expensive skincare products",
    "Facials and spa treatments",
    "Dermatologist visits",
    "Birth control for acne",
    "Collagen supplements",
    "Biotin supplements",
    "Laser treatments",
    "Dietary changes",
  ],
  fitness: [
    "Pre-workout supplements",
    "Creatine",
    "Protein powder",
    "BCAAs",
    "Fat burners",
    "Personal training",
    "Different workout programs",
    "More cardio",
    "More weight training",
    "Recovery supplements",
    "Testosterone boosters",
    "Changing gym",
  ],
  hair: [
    "Minoxidil (Rogaine)",
    "Finasteride (Propecia)",
    "Biotin supplements",
    "Collagen supplements",
    "Hair growth shampoos",
    "Essential oils",
    "Scalp treatments",
    "Laser combs/caps",
    "PRP treatments",
    "Iron supplements",
    "Vitamin D supplements",
    "Dermatologist consultations",
  ],
  immunity: [
    "Vitamin C supplements",
    "Zinc supplements",
    "Elderberry",
    "Echinacea",
    "Vitamin D",
    "Probiotics",
    "Garlic supplements",
    "Mushroom supplements",
    "Better sleep habits",
    "Exercise",
    "Reducing stress",
    "Healthy diet",
  ],
  resilience: [
    "Therapy/counseling",
    "Meditation apps",
    "Exercise",
    "Journaling",
    "Self-help books",
    "Yoga",
    "Stress management courses",
    "Better sleep",
    "Cutting back on work",
    "Vacation/time off",
    "Support groups",
    "Life coaching",
  ],
  libido: [
    "Maca root",
    "Tribulus terrestris",
    "Hormone testing",
    "Testosterone therapy",
    "Counseling",
    "Exercise",
    "Reducing stress",
    "Better sleep",
    "Relationship therapy",
    "Changing medications",
    "Ginseng",
    "Fenugreek",
  ],
  satiety: [
    "High-protein diet",
    "High-fiber foods",
    "Drinking more water",
    "Eating slowly",
    "Smaller plates",
    "Appetite suppressants",
    "Fiber supplements",
    "Glucomannan",
    "Meal timing strategies",
    "Mindful eating courses",
    "Protein powder",
    "Avoiding processed foods",
  ],
  default: [
    "Various supplements",
    "Lifestyle changes",
    "Diet modifications",
    "Exercise",
    "Sleep changes",
    "Mindfulness",
  ],
};

// Wellness goals (category-agnostic)
export const WELLNESS_GOALS = [
  "Better sleep quality",
  "More daily energy",
  "Reduced stress",
  "Improved focus",
  "Better overall health",
  "Weight management",
  "Enhanced recovery",
  "Mental clarity",
];

// Life stages
export const LIFE_STAGES = [
  "Student",
  "Early career professional",
  "Parent with young children",
  "Established professional",
  "Retired or semi-retired",
];
export const LIFE_STAGE_WEIGHTS = [0.1, 0.25, 0.25, 0.3, 0.1];

// Age ranges
export const AGE_RANGES = ["18-24", "25-34", "35-44", "45-54", "55-64", "65+"] as const;
export const AGE_WEIGHTS = [0.1, 0.3, 0.3, 0.2, 0.08, 0.02];

// Pain duration options
export const VILLAIN_DURATIONS = [
  "Less than 1 month",
  "1-6 months",
  "6-12 months",
  "1+ years",
];

// Tried other options
export const TRIED_OTHER_OPTIONS = [
  "No, this is my first",
  "Yes, 1-2 others",
  "Yes, several others",
];

// US States for location
export const US_STATES = [
  "California", "Texas", "Florida", "New York", "Pennsylvania",
  "Illinois", "Ohio", "Georgia", "North Carolina", "Michigan",
  "New Jersey", "Virginia", "Washington", "Arizona", "Massachusetts",
  "Tennessee", "Indiana", "Missouri", "Maryland", "Wisconsin",
];

// First and last names for simulation
export const FIRST_NAMES = [
  'Emma', 'Liam', 'Olivia', 'Noah', 'Ava', 'Ethan', 'Sophia', 'Mason',
  'Isabella', 'William', 'Mia', 'James', 'Charlotte', 'Benjamin', 'Amelia',
];
export const LAST_NAMES = [
  'Smith', 'Johnson', 'Williams', 'Brown', 'Jones', 'Garcia', 'Miller',
  'Davis', 'Rodriguez', 'Martinez', 'Anderson', 'Taylor', 'Thomas', 'Moore', 'Jackson',
];

/**
 * Get content for a specific category, with fallback to default
 */
export function getCategoryContent(category: string | undefined) {
  const cat = category || 'default';
  return {
    motivations: CATEGORY_MOTIVATIONS[cat] || CATEGORY_MOTIVATIONS.default,
    hopedResults: CATEGORY_HOPED_RESULTS[cat] || CATEGORY_HOPED_RESULTS.default,
    heroSymptoms: CATEGORY_HERO_SYMPTOMS[cat] || CATEGORY_HERO_SYMPTOMS.default,
    failedAlternatives: CATEGORY_FAILED_ALTERNATIVES[cat] || CATEGORY_FAILED_ALTERNATIVES.default,
    hopedOutcomes: CATEGORY_HOPED_OUTCOMES[cat] || CATEGORY_HOPED_OUTCOMES.default,
    archetypeQuotes: CATEGORY_ARCHETYPE_QUOTES[cat] || CATEGORY_ARCHETYPE_QUOTES.default,
  };
}

/**
 * Get category-specific quotes for a given archetype
 */
export function getArchetypeQuotesForCategory(
  category: string | undefined,
  archetype: ParticipantArchetype
): string[] {
  const cat = category || 'default';
  const categoryQuotes = CATEGORY_ARCHETYPE_QUOTES[cat] || CATEGORY_ARCHETYPE_QUOTES.default;
  return categoryQuotes[archetype] || categoryQuotes.struggler;
}

/**
 * Get category-specific hoped outcomes
 */
export function getHopedOutcomesForCategory(category: string | undefined): string[] {
  const cat = category || 'default';
  return CATEGORY_HOPED_OUTCOMES[cat] || CATEGORY_HOPED_OUTCOMES.default;
}

/**
 * Check if a category has specific content (vs falling back to default)
 */
export function hasSpecificCategoryContent(category: string): boolean {
  return category in CATEGORY_HERO_SYMPTOMS && category !== 'default';
}
